# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0002_auto_20170409_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
